### ISSUE TITLE
Update to 108?

### ISSUE THREAD

**Issue by Simpler1** [QuantumObject/docker-zoneminder#10]
Are there plans to update to 1.28.108 so that this can be used to test zmNinja desktop?

BTW, this works great.  Good work.

Thanks...

**Comment by angelrr7702** [comment]
Hi,

 I send a new build to docker .. that will install the last zoneminder from the PPA.
 Let me know if working ..At this moment unable to test it (I maybe have some time to test it on the weekend).. assuming that from .107 to .108 there aren't much difference that will brake the container but I can be wrong .

sincerely
Angel Rodriguez

**Comment by Simpler1** [comment]
Thanks, but now it doesn't work at all...   In the browser window, I'm getting:
`ZoneMinder is not installed properly: php's date.timezone is not set to a valid timezone`

**Comment by angelrr7702** [comment]
Yes, confirm the problem .. appear that new install PPA have problem with configuration of date.timezone at file /etc/php5/apache2/php.init ,

I have to add data.timezone = "America/New_York"  to make it work .. but it will define wrong timezone for everybody that not running server on that timezone .. The solution will need to be done by the PPA or zoneminder . or each user of zoneminder need to edit the file in question and add the correct timezone to it . 
file : /etc/php5/apache2/php.init 
;date.timezone =                            ==need to change==>   date.timezone="xxxxxxxx/xxxxx"
** where xxxxxx/xxxxxx need to be correct timezone ..

I already do the change to "America/New_York" for this container and I send it to build at docker repository ... I will check again when done .

sincerely
Angel Rodriguez

**Comment by angelrr7702** [comment]
done, working now .. but something else fail ...socket_sendto( /var/run/zm/zms-111238s.sock ) failed: No such file or directory

**Comment by angelrr7702** [comment]
this additional issue will be handled at : 

https://github.com/QuantumObject/docker-zoneminder/issues/11
