### ISSUE TITLE
howto preserve events

### ISSUE THREAD

**Issue by firsttris** [QuantumObject/docker-zoneminder#12]
hello

just wanted to ask whats the best practices to preserve zoneminder events in your docker container?

Is it possible to mount a folder to preserve them when container is delete/updated?

or do you basically work with mysql backup/restore?  
mysqldump -u root -pmysqlpsswd --all-databases > /var/backups/alldb_backup.sql
mysql -u root -pmysqlpsswd < /var/backups/alldb_backup.sql

regards
firsttris

**Comment by angelrr7702** [comment]
at this moment i don't have clear view how that will be done in the future .. I create a script and volume for backup ..   restore scrip still missing .. but there is a chance I move in the direction of docker way .. of doing it ... in that case maybe mysql will be separate from this container and link them (two container ) plus adding more volume for conf and data . I don't like because the objective of my container is to simplified deployment , at the same time docker change all the time . and each time I have to modified/review all my container .

**Comment by firsttris** [comment]
from looking at other zoneminder docker images:
https://hub.docker.com/r/aptalca/docker-zoneminder/

seems they just mount a folder to /config

while config is used as location for the hole zoneminder config:

/usr/share/zoneminder

when database is re-rolled seperately (with mysql dump restore 1 post..) all events should be back and working. 

-but i could be wrong

regards

**Comment by firsttris** [comment]
hello,

i did further testing and i think i achieved what i wanted...

i mounted the following 
(host:guest)
/media/red/docker/zoneminder/events:/var/cache/zoneminder/events
/media/red/docker/zoneminder/images:/var/cache/zoneminder/images
/media/red/docker/zoneminder/mysql:/var/backups

using this mount all events will be stored outside the container..
addtionally i ran mysqldump: 
mysqldump -u root -pmysqlpsswd --all-databases > /var/backups/alldb_backup.sql

for testing purposes i deleted my container and created a new one from the image.
after running the container (using the same mounts) and restoring mysqldump using:
mysql -u root -pmysqlpsswd < /var/backups/alldb_backup.sql

all events and zm-config is back!

regards
tristan

**Comment by falcon15500** [comment]
You can put the db files and the events/images out in their own volumes.  In that way, all the relevant stuff is saved if you destroy the container and re-create it.

**Comment by firsttris** [comment]
events and images folders in a own volume and bind-mount a host folder works well..

but i have some issue with mysql, no matter if i bind a volume to /var/lib/mysql or create a symlink to another volume ln -s /config/mysql /var/lib/mysql

zonminder always gives the following mysql issue:
Unable to connect to ZM db.SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

any idea?

**Comment by firsttris** [comment]
hello,

okay moving the mysql folder seems to be a better way:

        mv /var/lib/mysql /config
        ln -s /config/mysql /var/lib/mysql
        chown -R mysql:mysql /var/lib/mysql
        chmod -R go+rw /config

now i have images / events on a bind mount volume as well as the mysql folder.

i will do further tests (delete container etc.. and try to restore data) and report back
