### ISSUE TITLE
unable to get timeline working

### ISSUE THREAD

**Issue by firsttris** [QuantumObject/docker-zoneminder#13]
holla,

i was not able to get timeline working (using your latest version from dockerhub)

https://dl.dropboxusercontent.com/u/13344648/timeline.PNG

in mobile app (zmninja) its working perfect but webui chart is not displayed.

regards

**Comment by angelrr7702** [comment]
I add yesterday the --shm-size=4096m options when executing docket run , in that way you don't need to used --privileged=true (this only work for new docker 1.10)  but still need to check myself if that working . appear I forget to build it at docker hub .  About the webui before I have a lot of problem to make it work .. appear that there are different reason it fail : 

1)
need to edit config -> paths, and change:
"/cgi-bin/nph-zms"    to: "/zm/cgi-bin/nph-zms"

2) fix timezone at php.ini  ==> right now my container have America/New York before no was define and create failure on webui

3) if you change to authentication required to login OPT_USE_AUTH them webui fail if you don't change  AUTH_RELAY from "hashed" to "none"  and this make your site less secure for that reason I deploy under https (letsencrypt ) .  still need to find a way for fix it .

sincerely
Angel Rodriguez

**Comment by angelrr7702** [comment]
for that reason I deploy under https (letsencrypt )   ==>this no part of container but using 
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
and 
http://jasonwilder.com/blog/2014/03/25/automated-nginx-reverse-proxy-for-docker/

**Comment by angelrr7702** [comment]
You have reason , timeline not working .. checking

**Comment by firsttris** [comment]
1. i already set it to "/zm/cgi-bin/nph-zms"
2. i will test with my TimeZone Europe/Berlin
3. i already set it to AUTH_RELAY "none" <= is this a save option for remote access?

i found some debug infos in zm - forum maybe this helps?
https://forums.zoneminder.com/viewtopic.php?t=22704

regards

**Comment by firsttris** [comment]
after changing TimeZone - timeline seems to be working!

**Comment by firsttris** [comment]
for me it was additionally also neccesary to mount -v /etc/localtime:/etc/localtime:ro to get correct system time
