### ISSUE TITLE
Php date.timezone Issue With Zoneminder 1.29.0 in Ubuntu Server 15.04 64-Bit

### ISSUE THREAD

**Issue by Gbengat** [QuantumObject/docker-zoneminder#14]
Hi, 
I've been trying for about 2 days to install the said version of zoneminder on ubuntu server 15.04 64-Bit. I edited the php.ini file and put in the correct timezone, restarted apache, even rebooted the server but still get the error in my browser that says zoneminder wasn't installed properly and I should set the correct timezone in my php.ini. I would greatly appreciate any help that can be provided as I have several ip cameras I have been running on zoneminder with ubuntu server 14.

**Comment by angelrr7702** [comment]
What version of docker you are using over ubuntu?

I need to know more about the procedure you are fallowing to install it. 

sincerely
Angel Rodriguez

**Comment by Gbengat** [comment]
Hi, 
I do not have docker installed. As for the installation procedure, I followed the one [here](https://wiki.zoneminder.com/Ubuntu_Server_15.04_or_15.10_64-bit_with_Zoneminder_1.29.0_the_easy_way) on the wiki.

**Comment by Gbengat** [comment]
Ooops.. I just realized I posted this issue in the wrong repository. This is the docker-zoneminder project not zoneminder. Sorry about that. And thanks for your willingness to help.

**Comment by angelrr7702** [comment]
you can read procedure at the REAME.MD that show how to fix some problem relate to zoneminder .. my container is base on ubuntu and more sure are the same mis configuration you have now,  check other issue here that we have to deal with all this small problem to make it work .

**Comment by Gbengat** [comment]
Thank you angelrr7702 I finally managed to fix it :-)
