### ISSUE TITLE
MySQL issues

### ISSUE THREAD

**Issue by Dids** [QuantumObject/docker-zoneminder#18]
I'm currently getting the following error:
```Unable to connect to ZM db.SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)```

I'm essentially mounting /var/lib/mysql on the host, and even though I'm seeing the database files generated on the host, it's clearly not starting properly.

Any idea what could be wrong? I'd much rather have full data persistence, for easier redeployments etc.

**Comment by Dids** [comment]
Also seeing the following in MySQL logs:
```Fatal error: Can't open and lock privilege tables: Table 'mysql.user' doesn't exist```

I'm assuming it's a permission issue, but I've already tried broad permissions (777) on the host directory, which should've fixed those.

**Comment by angelrr7702** [comment]
Did you installed it recently from docker hub . ? I update it today 4/11/2016.

**Comment by angelrr7702** [comment]
Hi, 

 problem is maybe relate to : 

I'm essentially mounting /var/lib/mysql on the host,

you need to change permission  internal inside of the container  of that folder for the mysql be able to write on it .  normal it will be able to do that but you mounting it when run or create the container and more sure now is root:root .

the other folder you need for full data persistence is /var/cache/zoneminder , again need to change permission internally (maybe not , I take care of it at start.sh script of the container) and maybe /etc/zm/zm.conf  .

later in this month or next  when I finish moving all my container to new baseimage I will check to make sure to allow full data persistence . 

sincerely
Angel Rodriguez

**Comment by Dids** [comment]
Running the latest version of this image on Debian 8 host OS, Docker version 1.9.1-cs2, deploying through Docker Cloud.

Yes, it's a permission issue, but I tried forking the repo and modifying both the Dockerfile to add the mysql user to the administrators group (didn't work) as well as changing the mysql startup script to start it as root (didn't work). Neither seemed to work, even though I'm running a separate MySQL container for other projects just fine.

**Comment by angelrr7702** [comment]
change at Dockerfile will not fix it ... when container create by docker run or docker create it will impose your -V and that will be change permission after the Dockerfile ,  you need to change at startup.sh script this will be the first script that will run after you run the container ..  let me do the change on it , i hope this don't mess with something else .

I add to Dockerfile : 

 VOLUME /var/lib/mysql  /var/cache/zoneminder  

and to startup.sh : 

chown -R mysql:mysql /var/lib/mysql 

ok, building now.  but no sure if this will mess with pre-conf.sh script that used to modified and configured mysql . let me know if this working , need to wait for this container finish building at docker hub.

sincerely
Angel Rodriguez

**Comment by angelrr7702** [comment]
build done .  it suppose to work now . try it and let me know if any problem .

**Comment by angelrr7702** [comment]
if run without the -v option it will work fine but if include it will fail ... the problem it will overwrite the volume and the data already there it will be delete.

**Comment by angelrr7702** [comment]
I fix it , test it and working . But need to be tested with different situations..
