### ISSUE TITLE
ZM no longer starts with latest updates

### ISSUE THREAD

**Issue by falcon15500** [QuantumObject/docker-zoneminder#20]
Hi there,

Was previously running your image without issue and recently had cause to pull down the latest one.  Unfortunately now the zoneminder service in the container won't start.  The web page is available, however.

The errors in the /var/log/zm/zm.log file in the container are as follows:

```
Can't exec "sudo": No such file or directory at /usr/share/perl5/ZoneMinder/General.pm line 110.
Use of uninitialized value $output in scalar chomp at /usr/share/perl5/ZoneMinder/General.pm line 119.
Use of uninitialized value $output in concatenation (.) or string at /usr/share/perl5/ZoneMinder/General.pm line 120.
```

None of the zmc/zma daemons start.

Any ideas?  Anything I can do to help test, let me know.

Regards,

Mike

**Comment by angelrr7702** [comment]
did you try to migrate the database from preview version to the new deployment ?

**Comment by falcon15500** [comment]
I tried to keep the same (external) db.  As it was going from 1.29 to 1.29, I didn't think I needed to do anything?

**Comment by angelrr7702** [comment]
please explain how you connected the external database . give some example of command you used to run zoneminder container and how you run the new version ..using the external .. to have idea where is the problem.

**Comment by falcon15500** [comment]
Sure, no problem.  My database files are just connected via a docker volume.

```
docker run --restart=unless-stopped --name zm --net home -d --shm-size=4096m \
   -v /docker/zm/app:/usr/share/zoneminder \
   -v /docker/zm/database:/var/lib/mysql \
   -v /etc/localtime:/etc/localtime:ro \
   -v /storage/zoneminder/events:/var/cache/zoneminder/events \
   -v /storage/zoneminder/images:/var/cache/zoneminder/images \
   -v /docker/zm/php/php5:/etc/php5 \
   -e VIRTUAL_HOST=zm.nine-hells.net -e TZ='Australia/Sydney' \
   quantumobject/docker-zoneminder:latest
```

As you can see from the above, I externalise quite a few parts so that even if I shutdown and delete the zm instance - I can just fire a new one up and all the data, images etc will still be there.  Has been working without issue for months.

To grab the new version, I just stopped and deleted the instance and then deleted the image files.  Re-running the same run command above, pulled down the newest image from the repo and started it.

**Comment by angelrr7702** [comment]
-v /docker/zm/app:/usr/share/zoneminder  ==> this is not update , you are running the same application .  and it will fail because now it have wrong permission .. trying without that line .  and before make a copy backup /docker/zm/database and /storage/zoneminder/events /storage/zoneminder/images  , reason I made some modification and maybe it will mess with your old data .

**Comment by falcon15500** [comment]
The web app is in /docker/zm/app:/usr/share/zoneminder - surely this hasn't changed?  Aren't we going from 1.29 to 1.29?  And what permissions would be wrong - all these files have the correct permissions and UID/GID to run successfully?

I am doing as you ask (currently backing up) and will report the results.

**Comment by angelrr7702** [comment]
1.29 to 1.29.1
yes, permission maybe is right at some point I change that folder to www-data:www-data (but that done before you mount the volume) no sure that will keep the same .

**Comment by falcon15500** [comment]
I am an idiot. :)

It was actually fine...  Permissions and all.  Had I bothered to check in the zoneminder logs I would have seen:

`Version mismatch, system is version 1.29.1, database is 1.29.0, please run zmupdate.pl to update.`

And after I did that, there was a:

`Can't create missing temporary directory '/var/run/zm': Permission denied`

Which I created and chown to www-data.www-data and now it's up and running.

Thanks for your time (and your image!)

**Comment by angelrr7702** [comment]
ok, perfect .

you can   -v  xxx/xxx:/var/cache/zoneminder    the complete folder where you have /images and /events 

any way .. the new update container I have VOLUME /var/cache/zoneminder /var/lib/mysql  and I made sure that folder and database are present or it will create a new one.
