### ISSUE TITLE
SQL error adding new monitor

### ISSUE THREAD

**Issue by nilathj** [QuantumObject/docker-zoneminder#21]
I've done a brand new install of this docker container on Ubuntu server 16.04.  ZoneMinder Console - Running - default v1.29.1
I can access the zoneminder console, but when I try to add a new monitor I get:

SQL-ERR 'SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'V4LMultiBuffer' at row 1', statement was 'insert into Monitors set LinkedMonitors = '', Device = '/dev/video0', Channel = '0', Format = '255', Palette = '0', V4LMultiBuffer = '', V4LCapturesPerFrame = '1', Protocol = '', Host = '', Port = '80', Method = '', Options = '', Path = '', User = '', Pass = '', Colours = '3', Width = '320', Height = '240', Orientation = '0', Deinterlacing = '0', RTSPDescribe = '0', LabelFormat = '%N - %d/%m/%y %H:%M:%S', LabelX = '0', LabelY = '0', LabelSize = '1', ImageBufferCount = '50', WarmupCount = '25', PreEventCount = '25', PostEventCount = '25', StreamReplayBuffer = '1000', AlarmFrameCount = '1', EventPrefix = 'Event-', SectionLength = '600', FrameSkip = '0', MotionFrameSkip = '0', AnalysisUpdateDelay = '0', FPSReportInterval = '1000', DefaultView = 'Events', DefaultRate = '100', DefaultScale = '100', WebColour = 'red', Exif = '0', SignalCheckColour = '#0000c0', Name = 'Monitor-1', ServerId = '', Type = 'Local', Function = 'Monitor', Enabled = '1', AnalysisFPS = '', MaxFPS = '', AlarmMaxFPS = '', RefBlendPerc = '6', AlarmRefBlendPerc = '6', Sequence = 1'

I started docker using:
sudo docker run --restart=always -d -t --shm-size=4096m -p 80 quantumobject/docker-zoneminder

**Comment by nilathj** [comment]
I also get this when I try to add an ffmpeg source:

SQL-ERR 'SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'ServerId' at row 1', statement was 'insert into Monitors set LinkedMonitors = '', Name = 'Monitor-1', ServerId = '', Type = 'Ffmpeg', Function = 'Record', Enabled = '', RefBlendPerc = '6', AlarmRefBlendPerc = '6', AnalysisFPS = '', MaxFPS = '', AlarmMaxFPS = '', Device = '/dev/video0', Channel = '0', Format = '255', Palette = '0', V4LMultiBuffer = '', V4LCapturesPerFrame = '1', Protocol = '', Host = '', Port = '80', Method = 'rtpUni', Options = '', Path = 'rtsp://192.168.1.201//user=admin_password=wanker21_channel=1_stream=0.sdn', User = '', Pass = '', Colours = '3', Width = '320', Height = '240', Orientation = '0', Deinterlacing = '0', RTSPDescribe = '0', LabelFormat = '%N - %d/%m/%y %H:%M:%S', LabelX = '0', LabelY = '0', LabelSize = '1', ImageBufferCount = '100', WarmupCount = '25', PreEventCount = '25', PostEventCount = '25', StreamReplayBuffer = '1000', AlarmFrameCount = '1', SignalCheckColour = '#0000c0', EventPrefix = 'Event-', SectionLength = '600', FrameSkip = '0', MotionFrameSkip = '0', AnalysisUpdateDelay = '0', FPSReportInterval = '1000', DefaultView = 'Events', DefaultRate = '100', DefaultScale = '100', WebColour = 'red', Sequence = 1'

**Comment by nilathj** [comment]
It looks like in file /etc/mysql/mysql.conf.d/mysqld.cnf
I need to add:
sql_mode=NO_ENGINE_SUBSTITUTION

Refer:
https://forums.zoneminder.com/viewtopic.php?t=24609

**Comment by thotmobster** [comment]
I am running CentOS Linux release 7.2.1511 (Core) with this docker container and am seeing the same issue. I also tried sql_mode=NO_ENGINE_SUBSTITUTION in  /etc/mysql/mysql.conf.d/mysqld.cnf but error persisted. Any suggestions?

**Comment by angelrr7702** [comment]
Hi, 

  did you trying to used a device on the same server running docker container ?   

Device = '/dev/video0  appear on your error msg . did you can provide example of configuration for the new monitor . 

sincerely
Angel Rodriguez

**Comment by egyptianbman** [comment]
Looking at `ps aux`, I noticed that mysql was running with `--basedir=/usr`. It turns out that there's a `/usr/my.cnf` that you can update/replace/mount which is what mysql is using.

**Comment by angelrr7702** [comment]
Hi,

 I apologize for the time it took me to fix this problem with my container .. it broke after a update and a build and never release of the problem .. i was testing it with old version of the image and no aware of the problem .. and I was mis-reading/interpreting  the issue like other type of problem.   thanks for trying to let me know and all the time you took to find the problem with it and possible solution ..  in the end i have to modified file . /usr/my.cnf to fix GLOBAL sql_mode = NO_ENGINE_SUBSTITUTION problem .


sincerely
Angel Rodriguez

**Comment by nilathj** [comment]
All good. Thanks mate for the update. 

Cheers
Nilath.
