### ISSUE TITLE
2 Issues - MySQL sql_mode incorrect and /dev/shm not writeable by www-data

### ISSUE THREAD

**Issue by mikebski** [QuantumObject/docker-zoneminder#22]
# Problem 1

sql_mode is incorrect in MySQL.  Need to update the correct my.cnf file to have:

`sql_mode = NO_ENGINE_SUBSTITUTION`

To fix in a running container, replace `cid` below with the container id from `docker ps` and run the follwing:

`docker exec -it cid /bin/bash`
`mysql -uroot -pmysqlpsswd -e 'set GLOBAL sql_mode = NO_ENGINE_SUBSTITUTION'`

This is lost at restart, so it needs to be fixed in the container image.

# Problem 2

In the container, `/dev/shm` is not writable by user `www-data`.  Can be fixed by:

`docker exec -it cid /bin/bash`
`chown www-data /dev/shm`

There are several ways to fix this in the image, which needs to be done.  This is causing error: `Memory map file '/dev/shm/zm.mmap.1' does not exist. zmc might not be running.` in the log.

**Comment by angelrr7702** [comment]
thanks , I will update version and add your fix ...

**Comment by angelrr7702** [comment]
Hi,

 I apologize for the time it took me to fix this problem with my container .. it broke after a update and a build and never release of the problem .. i was testing it with old version of the image and no aware of the problem .. and I was mis-reading/interpreting  the issue like other type of problem.   thanks for trying to let me know and all the time you took to find the problem with it and possible solution ..  in the end i have to modified file . /usr/my.cnf to fix GLOBAL sql_mode = NO_ENGINE_SUBSTITUTION problem .


sincerely
Angel Rodriguez
