### ISSUE TITLE
doesn't install zoneminder 1.30 or ubuntu 16.04

### ISSUE THREAD

**Issue by yajrendrag** [QuantumObject/docker-zoneminder#25]
thanks for your image..

for me, it installed zoneminder 1.29.1 on ubuntu 15.10.  Are you still working on an update?

Also, any chance you could help suggest how i might store zoneminder data on a different drive?  docker is running on my boot drive which is an ssd but i have a few other larger (spinning) drives - would i simply link or bind mount /var/lib/docker to some other location?  or is there a better way to do this sort of thing with docker?

thanks.

**Comment by angelrr7702** [comment]
Yes. I update container  but is not the one you are referring the problem appear that I'm trying  quantumobject-zoneminder:test  for 1.30.2 and ubuntu 16.04 (still no ready) but docker hub build for some reason put README.MD for this test build like the Official build of the container .

VOLUME /var/lib/mysql   /var/cache/zoneminder  ==> at zoneminder  Dockefile

You can use -v  /Users/<path>/mysql: /var/lib/mysql -v /Users/<path>/zoneminder:/var/cache/zoneminder  , please test it first maybe will no work like i expected it (I almost never used it) ... 

check this link for other options : 
https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-directory-as-a-data-volume

sincerely

Angel Rodriguez

**Comment by yajrendrag** [comment]
Thanks for your answer.  i am new to docker so trying to wrap my head around it.. i follow your suggestions to use the -v options on the docker run command line.  Do i also need to comment out the VOLUME line in the dockerfile?  & if so, to do that do i need to make my own version of it first?

& since i've already added data to the system i have been using docker start to restart the image if for some reason i stopped it.  How would i move the data to a new image - committing seems to do no good here.

thanks again.

-jay

**Comment by yajrendrag** [comment]
ok, i made some progress - i was able to find the data from existing system and copy it to the host directories i want to persist.  then did a docker run using the -v options - works just like a mount in that it overlays whatever is in those locations in the containers.

so only remaining question is how to upgrade the image when you release a new one... but now that i've got the data persisting on host storage, i can probably trash the original image and deploy a new one... or at least that seems to be one way to go about it.  let me know if there's a better way.

thanks again for your help and the image!

**Comment by angelrr7702** [comment]
glad to know that work for you ... before run the new image create a backup for your data on separate location of the one you will used for -v options ... in case my container destroy the data for any problem with it ... test it before to do the move to make sure it is working correctly ... and let me know of any problem with it to try to find a solutions for it.   Next upgrade, when able to do it (i have some problem with it) ,  change version of mysql that maybe create some problem for upgrade ... (default version for Ubuntu 16.04)

**Comment by angelrr7702** [comment]
reference to fix container with mysql 5.7 for ubuntu 16.04
https://github.com/mysql/mysql-docker/blob/mysql-server/5.7/docker-entrypoint.sh

**Comment by swissglider** [comment]
any news on the update ? I still get the 1.29

**Comment by swissglider** [comment]
No further plan for 1.3 ?

**Comment by angelrr7702** [comment]
sorry for delay ..., working on it ...

**Comment by angelrr7702** [comment]
done, new version 1.31.1 available for my container ..  I have to used mariadb for mysql ..to make it work ..now Ubuntu 16.04 . please let me know of any problem with it ...
