### ISSUE TITLE
Cam connection

### ISSUE THREAD

**Issue by p1o2i3u4** [QuantumObject/docker-zoneminder#26]
Hello, 

I have a cam that streams ffmpeg (xiaofang) which connects fine if I install zoneminder on debian, but using this docker on XPEnology, I cannot get it to connect. 

I have set the proper paths to ffmpeg encode/decode, checked the box, and added cams as follows
ffmpeg, rtsp://ip:port/unicast, RTSP/RTP. This same setting works on debian zoneminder.

Do i have to map any other ports than web interface?

I can add internet streams, though. 

Please help!

**Comment by angelrr7702** [comment]
proper paths : 
  /usr/bin/ffmpeg
before was : 
  /usr/local/bin/ffmpeg

please try both options and let me know if any of them fix the problem.

and please send me a copy of the logs from zoneminder top rigt side .... 

sincerely
Angel Rodriguez

**Comment by p1o2i3u4** [comment]
http://www.filedropper.com/zm-log1

here it is. Neither works. zm 1 keeps on crashing.

thank you!

**Comment by ssy080** [comment]
Do you have any recommendations? I still haven't figured this out. Please and thank you
