### ISSUE TITLE
Docker failing to create socket

### ISSUE THREAD

**Issue by Kaju-Bubanja** [QuantumObject/docker-zoneminder#27]
I tried everything as described in the info page: Change the path to the correct one. Now if I enter the username:pw@ip and port and host path. I get the error
 getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-132190s.sock ) failed: No such file or directory when I try to access the live view.

**Comment by angelrr7702** [comment]
I update container to 1.31.1 , I never was able to create your problem ... please let me know if new version have the same problem ... before I give this recommendation : 

"and if you change System=> "Authenticate user logins to ZoneMinder" you at this moment need to change "Method used to relay authentication information " to "None" if this not done you will be unable to see live view. This only recommended if you are using https to protect password(This relate to a mis-configuration or problem with this container still trying to find a better solutions)." 

Still need to check if that apply for this version .

sincerely
Angel Rodriguez

**Comment by angelrr7702** [comment]
container modified , now need to run another container with database mysql . please check how this affect you
