### ISSUE TITLE
Allow acess mysql

### ISSUE THREAD

**Issue by thiagolsfortunato** [QuantumObject/docker-zoneminder#28]
Good afternoon,

How do I free remote access to port 3306 from mysql inside Container Zoneminder? I created an api that does CRUD.

Thiago Fortunato
thiago.fortunato@fotosensores.com

**Comment by angelrr7702** [comment]
you are welcome to fork and separate mysql from the container ... in other word will be needed to run two container where mysql container is link to the zoneminder container.

**Comment by thiagolsfortunato** [comment]
I would to use only one container, but couldn't acess. Then, I did wichi you said and can be add, remove and update the configurations of cameras.

To allow remote acess you need to edit my.cnf add 'bind_address = 0.0.0.0' and restart mysql service also grant to user you will acess de database:

GRANT ALL PRIVILEGES ON database.* TO 'user'@'%' identified by 'password' WITH GRANT OPTION;

**Comment by angelrr7702** [comment]
Container update to version 1.31.1 , I have to used MariaDB to fix problem with mysql 5.7 relate to configuration. No idea how this will affect ....

**Comment by angelrr7702** [comment]
update again and give more privileges for database ... create, delete, lock , etc ..

**Comment by jjanderson** [comment]
Hello, Sorry for the noob question, but how do I access the DB to import camera's etc?

Thanks

**Comment by thiagolsfortunato** [comment]
@jjanderson Using mysql run this command to acess mysql in container zoneminder:

```
docker exec -it zoneminder mysql -u zmuser -p zmpass
```

**Comment by jjanderson** [comment]
HI, thanks for the quick response. When I use putty to ssh into the host, I get the following error: Error response from daemon: No such container: zoneminder

I am running docker on a synology NAS.

**Comment by thiagolsfortunato** [comment]
@jjanderson You need to change `zoneminder` to name of your container Zoneminder.
 i can't undertand, why you use putty into the host?

**Comment by jjanderson** [comment]
Hi, How would you suggest I connect? There is a UI for Docker in Synology but terminal says I dont have access...

**Comment by thiagolsfortunato** [comment]
To connect on Synology from your host you need putty. After that, try execute docker comands with `sudo` or  `root` user.

**Comment by jjanderson** [comment]
Hi, I have now got a bit further with this, however I am getting now the following... (I use the admin zmuser and have double checked the password)

```
Enter password:
ERROR 1045 (28000): Access denied for user 'admin'@'localhost' (using password: YES)
ash-4.3#
```

**Comment by thiagolsfortunato** [comment]
According to Zoneminder's documentation, the user and password used to access the db are:
```
user: zmuser
pass: zmpass
```

**Comment by jjanderson** [comment]
Nope, still get access denied... I am running the container without any modification... all I did was spin up the container, and now my next step was to import my monitors, which I usually do via phpmyadmin, however having it all in one container which is not connected to my database makes getting into the database difficult for me

**Comment by thiagolsfortunato** [comment]
I understood, when I used Zoneminder, I needed to create another database, because my application was responsible for persisting the data from the cameras / monitors, so I do not use the Zoneminder API.
But even so, I followed the scripts used by the documentation and worked.

**Comment by jjanderson** [comment]
I just need to know how to access the db within this docker container so that I can import my monitors... mysql is within this container and thus not in my host SQL database.... So, apologies for the noob questions again, but the question in iteself is pretty simple.... How do I access the DB within this docker container in order to import my monitors.sql file?

**Comment by thiagolsfortunato** [comment]
1 - Acess container Zoneminder:
```
$ docker exec -it [container-zoneminder] bash
```
2 - Inside the container run, add folloing line in `/etc/mysql/my.cnf`, this allow to access mysql outside the container :

```
bind-address = 0.0.0.0
```
3 - Get out the container and create another Image Zoneminder Docker based this container with you already done edited:

```
$ docker commit [container-zoneminder] [new-image-zoneminder]:[tag]
```

4 - Create container using new Zoneminder Image, exposing mysql port `3306`:

```
$ docker run -p 3306:3306 -p 80:80 --name new-zoneminder new-image-zoneminder-docker
```

5 -Access mysql inside the zoneminder container :

```
docker exec -it new-zoneminer mysql -u zmuser -p zmpass
```

**Comment by angelrr7702** [comment]
mysql was separate from container please check how these will affect your case;  to run container now need to create mysql container first please check documentation change ...

**Comment by jjanderson** [comment]
Hi,

So I followed the new instructions, creating db container and then ZM container, and they are both showing in my Synology Docker UI as running. (I had toi change the ZM ports, but that was my only deviation using these command sets:

```
docker network create net
docker run -d -e TZ=Europe/Jersey -e MYSQL_USER=zmuser -e MYSQL_PASSWORD=zmpass -e MYSQL_DATABASE=zm -e MYSQL_ROOT_PASSWORD=mysqlpsswd -e MYSQL_ROOT_HOST=% --net net --name db mysql/mysql-server:5.7
echo "wait until MySQL startup..."
docker run -d --shm-size=4096m -e TZ=Europe/Jersey -e ZM_DB_HOST=db --net net --name zm -p 82:82 quantumobject/docker-zoneminder
```

However, when I go to the url <hostip>:82/zm I get page not found... 

Any ideas?

Also, then in terms of accessing and updating the monitors table in mysql, how (following on from the seperate container) do I get to an interface where I can simply update the monitrs table with my previous export/backup?

Thanks

**Comment by angelrr7702** [comment]
fix a problem with apache2 configuration.

**Comment by jjanderson** [comment]
THis is on a vanilla install. None of my other docker containers seem to have this issue. Could you detail any apache2 requirements or configurations?

Thanks

**Comment by maskott** [comment]
@jjanderson I'm wondering if maybe it is the ports you specified.  On that last `docker run` command, you specified `-p 82:82`.  Unless you modified Docker to be running on port 82, it should default to 80.  I use `-p 99:80` in my `run` command and then access everything at http://<ip>:99/zm  - Perhaps you just need to edit the `run` command to `-p 82:80`?

**Comment by angelrr7702** [comment]
closing this issue , database was move out from container ..
