### ISSUE TITLE
Api Update - zmNinja

### ISSUE THREAD

**Issue by Dulanic** [QuantumObject/docker-zoneminder#35]
Is there any way to pull the latest API version so the 24 hour view works with zmNinja?

https://github.com/pliablepixels/zmNinja/wiki/FAQ#zmninja-12515-and-beyond-says-need-api-upgrade-for-the-24hr-review-feature-what-does-that-mean

Just needs the latest EventsController.php from 
https://raw.githubusercontent.com/ZoneMinder/ZoneMinder/master/web/api/app/Controller/EventsController.php

**Comment by angelrr7702** [comment]
I update the container please check that fix api problem ..

**Comment by Dulanic** [comment]
Sorry for delay, yes this did.
