### ISSUE TITLE
Install ssmtp

### ISSUE THREAD

**Issue by giannivh** [QuantumObject/docker-zoneminder#36]
I couldn't get email notifications to work. Turns out ssmtp is not installed:

https://wiki.zoneminder.com/How_to_get_ssmtp_working_with_Zoneminder

Could you by default install it? 

We could then map 
`-v /host/path/zoneminder/ssmtp:/etc/ssmtp`
for our config to work.

**Comment by angelrr7702** [comment]
you are welcome for fork it and add ssmtp ...  container become too big ... at the moment ... only for testing and learning how to used it (no final deployment for zoneminder) ...  you can access the container directly  and add the package too... by docker exec -it container_id /bin/bash .... 

sincerely
Angel Rodriguez

**Comment by loganto** [comment]
@angelrr7702 Do uknow if there is a ready made docker for final ZM deploys? this docker is the best one I could find on docker hub.

**Comment by asantaga** [comment]
Hey Loganto, Im working on this in my fork of this image.. should have it done soon and then I'll open a PR for this image

**Comment by bkjaya2020** [comment]
I have managed  to use  ssmtp with  QuantumObject / docker-zoneminder . For the installation details please refer this link.
[](https://bkjaya.wordpress.com/2019/11/27/how-to-use-ssmtp-mta-within-a-docker-zoneminder-containeron-ubuntu-19-10/)

**Comment by angelrr7702** [comment]
installed but you need to follow the link provide by https://github.com/bkjaya2020 before to configured it.   https://bkjaya.wordpress.com/2019/11/27/how-to-use-ssmtp-mta-within-a-docker-zoneminder-containeron-ubuntu-19-10/
