### ISSUE TITLE
./startup.sh: line 38: syntax error near unexpected token `fi'

### ISSUE THREAD

**Issue by clueo8** [QuantumObject/docker-zoneminder#43]
I tried starting this up but it fails with:
./startup.sh: line 38: syntax error near unexpected token `fi'

Also, I see maria-db in the image, but yet the instructions want us to create a mysql instance before hand... Is the documentation needing to be updated?  I'd like to run this with my existing mysql container...

**Comment by angelrr7702** [comment]
fix , problem was that container was modified to separate mysql to be run separated and forget to remove a line , please check documentation of my container for the change .
