### ISSUE TITLE
Correct syntax error 'unexpected token fi'

### ISSUE THREAD

**Issue by brainkiller** [QuantumObject/docker-zoneminder#44]
https://github.com/QuantumObject/docker-zoneminder/blob/e0f4640000b8311c78f96f9838ee9d4be9c4fcd7/startup.sh#L38

docker-zoneminder fails to start because of a syntax error:
```
Starting pre-service scritps in /etc/my_init.d
*** Running: /etc/my_init.d/startup.sh
/etc/my_init.d/startup.sh: line 38: syntax error near unexpected token `fi'
*** Failed with return value: 2

```

**Comment by angelrr7702** [comment]
fix , problem was that container was modified to separate mysql to be run separated and forget to remove a line  , please check documentation of my container for the change .
