### ISSUE TITLE
Run zmupdate.pl

### ISSUE THREAD

**Issue by Guglio95** [QuantumObject/docker-zoneminder#46]
Hi, 
I think you should run zmupdate.pl in startup.sh,
My installation was broken after I upgraded to your last docker image because database's zm schema version was not the same of images' one.

**Comment by angelrr7702** [comment]
did you needed it to start a new container with a new database or did you are trying to move old data to the new container ?
did need to to be run each time the container start or only the first time it is run and configured ?

sincerely
Angel Rodriguez

**Comment by Guglio95** [comment]
Hi, i ‘ve moved the db outside the image, using a mariadb container.
I’ve run it only once, the first time

**Comment by angelrr7702** [comment]
ok, add the script to be run only once first time ,
