### ISSUE TITLE
Some kind of permissions issue on cached assetts

### ISSUE THREAD

**Issue by thoraxe** [QuantumObject/docker-zoneminder#47]
`[Tue May 29 17:51:39.042819 2018] [authz_core:error] [pid 239] [client 10.88.0.1:59732] AH01630: client denied by server configuration: /var/cache/zoneminder/cache/skins_classic__css_classic_jquery-ui-theme-classic-1525810197.css`

I'm not sure why this would be the case.

Tried to `+Indexes` on `/zm/cache` and still got an error:

`[Tue May 29 17:57:43.798865 2018] [authz_core:error] [pid 444] [client 10.88.0.1:32856] AH01630: client denied by server configuration: /var/cache/zoneminder/cache/`

It appears additional directives may be required (Default in newer apache may be deny):

```
   Order allow,deny
   Allow from all
   # New directive needed in Apache 2.4.3: 
   Require all granted
```

From https://stackoverflow.com/questions/10351167/apache-client-denied-by-server-configuration#13923526

Adding those directives to the `directory` made things work:

```
<Directory /var/cache/zoneminder/cache>
   Order allow,deny
   Allow from all
   # New directive needed in Apache 2.4.3: 
   Require all granted
  Options -Indexes +FollowSymLinks
</Directory>
```

**Comment by thoraxe** [comment]
This may actually be an upstream bug:

https://github.com/ZoneMinder/zoneminder/blob/3c225c9f1c1a6ade63c1b7702d6178abacde1a21/distros/ubuntu1604/conf/apache2/zoneminder.conf#L9-L13

**Comment by civersen** [comment]
Have the same issue, your solution worked - thanks @thoraxe

**Comment by angelrr7702** [comment]
thanks for helping to find problem and solution. container fix now ..
