### ISSUE TITLE
[RFE] enable ZM_BASE_URL via env var

### ISSUE THREAD

**Issue by thoraxe** [QuantumObject/docker-zoneminder#50]
https://github.com/ZoneMinder/zoneminder/blob/master/web/index.php#L65

ZoneMinder accepts a ZM_BASE_URL parameter which is useful for putting ZM behind a reverse proxy.

When using `podman` which is an alternative to Docker, you can run the containers not bound to the host network, and then use an nginx container as a reverse proxy onto localhost which can make things safer overall.

In the interim I can kluge mounting a custom index.php into the container, but being able to set it via an env var would be awesome.

**Comment by thoraxe** [comment]
Actually `ZM_BASE_URL` doesn't even do what it's supposed to do:

https://github.com/ZoneMinder/zoneminder/issues/2127

**Comment by angelrr7702** [comment]
Yes. I run already that way using nginx container and let encrypt container ...

note: deploy this container behind proxy with SSL for extra security:

https://github.com/jwilder/nginx-proxy

https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
