### ISSUE TITLE
"/var/lib/mysql" no longer exposed?

### ISSUE THREAD

**Issue by moorsey** [QuantumObject/docker-zoneminder#57]
Just upgrading my container from an older version (1.30 I think).

I stopped the old container, updated base image and then re-ran my "docker run" command.  Stalls for a long time, then fails as follows:

`docker logs --follow zoneminder2
Starting pre-service scritps in /etc/my_init.d
*** Running: /etc/my_init.d/startup.sh
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
*** Failed with return value: 1`

After looking again, I can see that "/var/cache/mysql" is no longer exposed from the container, so obviously there has been a fundamental change here and the DB is no longer stored externally.  Kills my plan for an easy upgrade!

Just wanted to check I wasn't missing anything obvious, as can't see this mentioned anywhere as something to be aware of when upgrading.

Can see there is a sample command for running mysql in a separate container, so will give that a go.  Assuming a DB can be imported into a container from a local file easy enough!

Cheers all

**Comment by angelrr7702** [comment]
yes. I have to move database separate container ..  no internal database .
