### ISSUE TITLE
After upgrade, Privacy policy cannot be accepted

### ISSUE THREAD

**Issue by mrhanman** [QuantumObject/docker-zoneminder#60]
After upgrading the container, The privacy policy is displayed, but clicking accept only reloads the page with the privacy policy again.  The following is in the apache error log multiple times.

`[Sun Oct 07 01:32:42.447085 2018] [php7:warn] [pid 191] [client 192.168.x.x:15487] PHP Warning:  Use of undefined constant ZM_SHOW_PRIVACY - assumed 'ZM_SHOW_PRIVACY' (this will throw an Error in a future version of PHP) in /usr/share/zoneminder/www/index.php on line 231
[Sun Oct 07 01:32:42.447748 2018] [php7:warn] [pid 191] [client 192.168.x.x:15487] PHP Warning:  symlink(): No such file or directory in /usr/share/zoneminder/www/includes/functions.php on line 2085`

**Comment by Swicegood** [comment]
For a workaround, bash into the container and run zmupdate.pl

**Comment by angelrr7702** [comment]
Please re-open if you still find this problem ..
