### ISSUE TITLE
Don't hardcode root msyql user

### ISSUE THREAD

**Issue by ohcibi** [QuantumObject/docker-zoneminder#62]
In startup.sh on line 24 the mysql user `root` is hardcoded into the script. This must be replaced with a variable. Like this the image can't be considered production ready.

**Comment by Germs2004** [comment]
Why did this get closed?  It seems this dockerfile still uses "root" even though I've passed in a mysql user that has full pemissions on the zoneminder database.  Instead of requiring root, it should use the user that we passed in to "ZM_DB_USER".  If that user doesn't have the necessary permissions, throw an error.

**Comment by angelrr7702** [comment]
line that are relate to used of ROOT at container  : 

echo "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION';" | mysql -u $MYSQL_ROOT -p$MYSQL_ROOT_PASSWORD -h $ZM_DB_HOST -P$ZM_DB_PORT

mysql -u $MYSQL_ROOT -p$MYSQL_ROOT_PASSWORD -h $ZM_DB_HOST -P$ZM_DB_PORT $ZM_DB_NAME < /usr/share/zoneminder/db/zm_create.sql 

mysql -u $MYSQL_ROOT -p$MYSQL_ROOT_PASSWORD -h $ZM_DB_HOST -P$ZM_DB_PORT -e "grant all on $ZM_DB_NAME.* to '$ZM_DB_USER'@$ZM_DB_HOST identified by '$ZM_DB_PASS';"

**Comment by angelrr7702** [comment]
new provisional container build at docker hub to test without root and root password for zoneminder .
quantunobject/docker-zoneminder:fix

required to add --sql-mode="" to docker run command for mysql database or mariadb and MYSQL_USER and MYSQL_PASSWORD plus the full permission to modified the database create for zoneminder .

example :

docker run -d -e TZ=America/New_York -e MYSQL_USER=zmuser -e MYSQL_PASSWORD=zmpass -e MYSQL_DATABASE=zm -e MYSQL_ROOT_HOST=% --net net --name db mysql/mysql-server:5.7 --sql-mode=""

docker run -d --shm-size=4096m -e TZ=America/New_York -e ZM_DB_HOST=db --net net --name zm -p 80:80 quantumobject/docker-zoneminder:fix

when done testing modification will be move to master and 1.34 and 1.32 version .

sincerely
Angel Rodriguez

**Comment by angelrr7702** [comment]
fix move to master and 1.32. and 1.34 container version . You don't need MYSQL_ROOT_PASSWORD anymore to deploy container .
