### ISSUE TITLE
branch versioning

### ISSUE THREAD

**Issue by der-andrew** [QuantumObject/docker-zoneminder#66]
Please, consider to implement versioning of branches. By DB version for example. It's very important for multiple (50+) installations. I'd like to be sure all of my future installations have the same database version as previouse ones.

**Comment by angelrr7702** [comment]
Create two branch still need to make sure they  work fine .

## Branch Available at the moment 
quantumobject/docker-zoneminder:1.32
quantumobject/docker-zoneminder:1.34

sincerely
Angel Rodriguez
