### ISSUE TITLE
mysql on port 3307

### ISSUE THREAD

**Issue by htpcBeginner** [QuantumObject/docker-zoneminder#72]
My mariadb runs on Synology NAS on port 3307. Is there a way to manually specify say ZM_DB_PORT?

**Comment by angelrr7702** [comment]
for future reference https://forums.zoneminder.com/viewtopic.php?t=17693

**Comment by angelrr7702** [comment]
-e ZM_DB_PORT=3307 suppose to work now after I modified the container for 1.34 and default (master) .... for quantumobject/docker-zoneminder 

let me know of any problem ...
