### ISSUE TITLE
php does not update timezone 

### ISSUE THREAD

**Issue by DCandE** [QuantumObject/docker-zoneminder#80]
I get this error in log first deploy of 1.34

`
docker run -d --shm-size=4096m -e TZ=America/Chicago -e ZM_DB_HOST=db --net net --name zm -p 80:80 quantumobject/docker-zoneminder:1.34
`

`
2020-01-22 21:19:23 | web_php |   | 181 | ERR | ZoneMinder is not configured properly: php's date.timezone +0000 does not match the system timezone -0600! Please check Options->System->Timezone. | /usr/share/zoneminder/www/includes/functions.php | 2402
`

**Comment by angelrr7702** [comment]
It appear that need to be the same timezone for
 
php.ini
mysql 
/etc/timezone

I modified the one at /etc/timezone , rebuilding container and I will check tomorrow if that fix it .

**Comment by angelrr7702** [comment]
No that fail to fix it , appear that need to be done manual by  configuration at Options -> System -> Timezone change from default (GMT) UTC to your timezone.

sincerly
Angel Rodriguez
