### ISSUE TITLE
Please rebuild image to bring in changes from 1.34.2

### ISSUE THREAD

**Issue by gdunstone** [QuantumObject/docker-zoneminder#82]
1.34.2 is out.

Can this image please be rebuilt and published to dockerhub?

Is it easy to publish minor versions automatically?

**Comment by gdunstone** [comment]
https://github.com/ZoneMinder/zoneminder/releases/tag/1.34.2

**Comment by marcelo-ochoa** [comment]
Also please tag docker image tag using 1.34.2 format to align with zm_update-1.34.nn.sql file releases in /usr/share/zoneminder/db directory.
Thanks a lot. Marcelo.

**Comment by angelrr7702** [comment]
it is rebuild and will be  publishing when done to dockerhub  for 1.34.5

**Comment by marcelo-ochoa** [comment]
Builds at hub.docker.com still with tag without a minor release number
Last updated2 days ago by quantumobject   1.34
￼   docker pull quantumobject/docker-zoneminder:1.34

**Comment by angelrr7702** [comment]
yes. 1.34 .. is the one now with 1.34.5 version ... I used zoneminder compile from  http://ppa.launchpad.net/iconnor/zoneminder-1.34/ubuntu for building this container ,

**Comment by angelrr7702** [comment]
branch 1.34-db-fix will be used to test and build to fix this problem and others , it will keep separate from main master and 1.34 , only when work correctly it will be merge . at the moment no build from it at docker hub .. only to be build local .
