### ISSUE TITLE
Failure to log in

### ISSUE THREAD

**Issue by Germs2004** [QuantumObject/docker-zoneminder#87]
Fresh install using this command:
```
docker create \
	  --name zoneminder \
	  --restart=unless-stopped \
	  -p 1080:80 \
	  -p 1081:443 \
	  -e TZ='America/New_York' \
	  -e ZM_DB_HOST=$dbservername\
	  -e ZM_DB_NAME=$NEWDBNAME \
	  -e ZM_DB_USER=$NEWDBUSERNM \
	  -e ZM_DB_PASS=$NEWDBUSERPW \
	  -e ZM_DB_PORT=3306 \
	  -e MYSQL_ROOT=$ROOTUSR \
	  -e MYSQL_ROOT_PASSWORD=$ROOTPWD \
	  -v /home/me/zoneminder/events:/var/lib/zoneminder/events \
	  -v /home/me/zoneminder/logs:/var/log/zm \
	  --shm-size="512m" \
	  --net db-network \
	  quantumobject/docker-zoneminder:latest
```

I accessed the site at http://host:1080/zm, went to Options, and the only thing I changed was I checked the box for Authenticate Logins.  When I clicked Save on that Options page, it took me to the ZoneMinder login page.  When I enter the default admin;admin and click Login, I get a browser error.  I tried multiple times, including typing a fake password on purpose, and still get the same result.  I can't get into ZoneMinder.

Here is the browser error that briefly appears in the browser console and then disppears:
```
Uncaught TypeError: Cannot read property 'type' of undefined
at setFieldValue (onloadwff.fs:71)
at HTMLFormElement.formKeydownListener (onloadwff.js:71)
```
When that error disappears, the page displayed changes from the login form to a page that just says:
```
This page isn’t working
myhostname is currently unable to handle this request.
HTTP ERROR 500
```
That error page puts this in the browser's address bar (note the question mark):
`http://myhostname:1080/zm/?`

Restarting the docker container does not help me get past the login page.

**Comment by angelrr7702** [comment]
unable to duplicate ,  I try different combination and still nothing ,.. did you can provide more info relate to your system and database container ?

**Comment by Germs2004** [comment]
Ok, I'll try to give every detail to reproduce.

I'm running Windows 10 with Hyper-V installed.  A VM named "podman" running Ubuntu Server 19.10 is installed on Hyper-V.  On podman, I've installed Docker.  On that Docker instance, I have one container running "linuxserver/mariadb:latest", and another container running this "quantumobject/docker-zoneminder:latest" image.  I have the problem using all 3 of my browsers: Google Chrome, FireFox, and Microsoft Edge from my Windows 10 PC.

To reproduce:
1) Delete any existing zm database and zm user from the mariadb server.
2) Delete any existing zm container from docker.
3) Run this bash script with sudo on podman (the docker host).  It will create a blank zm database and user, and give that user full permission on that database.  With the latest version of your image, if we don't pre-create the db and user, it will fail to start.  This script will also create and start a zoneminder container from your image.

```
#!/bin/bash

DatabaseContainerName="mariadb"
DatabaseContainerPort=3306
ROOTUSR="root"
ROOTPWD="1vZL1lhekmoCYbUG478jVFsje89Cj2"
NEWDBNAME="zoneminder"
NEWDBUSERNM="myzmuser"
NEWDBUSERPW="kDTZ0bCIvfsIPY6nWDDDfVk2SQ4JIe"
		
NEWDBMISSING=$(sudo docker exec -i $DatabaseContainerName mysql -u$ROOTUSR -p$ROOTPWD --batch --skip-column-names -e "SHOW DATABASES LIKE '"$NEWDBNAME"';" | grep "$NEWDBNAME" > /dev/null; echo "$?")

if [[ $NEWDBMISSING == 1 ]]; then
	printf "${YELLOW}Creating new database and user: $NEWDBNAME${NORMAL}\n"
	docker exec -i $DatabaseContainerName mysql -u$ROOTUSR -p$ROOTPWD -e "CREATE DATABASE ${NEWDBNAME} DEFAULT CHARACTER SET latin1;" # latin1 charset is necessary to be compatible with Visual Studio Migrations feature
	docker exec -i $DatabaseContainerName mysql -u$ROOTUSR -p$ROOTPWD -e "CREATE USER '${NEWDBUSERNM}'@'%' IDENTIFIED BY '${NEWDBUSERPW}';"
	docker exec -i $DatabaseContainerName mysql -u$ROOTUSR -p$ROOTPWD -e "GRANT ALL PRIVILEGES ON ${NEWDBNAME}.* TO '${NEWDBUSERNM}'@'%';"
	docker exec -i $DatabaseContainerName mysql -u$ROOTUSR -p$ROOTPWD -e "FLUSH PRIVILEGES;"
else
	printf "${YELLOW}Database already exists: $NEWDBNAME${NORMAL}\n"
fi

docker pull quantumobject/docker-zoneminder:latest

docker create \
  --name zoneminder \
  --restart=unless-stopped \
  -p 1080:80 \
  -p 1081:443 \
  -e TZ='America/New_York' \
  -e ZM_DB_HOST=$DatabaseContainerName \
  -e ZM_DB_PORT=$DatabaseContainerPort \
  -e ZM_DB_NAME=$NEWDBNAME \
  -e ZM_DB_USER=$NEWDBUSERNM \
  -e ZM_DB_PASS=$NEWDBUSERPW \
  -e MYSQL_ROOT=$ROOTUSR \
  -e MYSQL_ROOT_PASSWORD=$ROOTPWD \
  -v /home/jeremy/zoneminder/events:/var/lib/zoneminder/events \
  -v /home/jeremy/zoneminder/logs:/var/log/zm \
  --shm-size="512m" \
  --net db-network \
  quantumobject/docker-zoneminder:latest

docker start zoneminder
```

I got these results from running that script:
![image](https://user-images.githubusercontent.com/5519340/76873574-4735e280-6844-11ea-9b13-1c55f1305192.png)

4) Access zoneminder via this url: http://podman:1080/zm
5) It takes you to the "ZoneMinder - Privacy" page
6) Click Apply to get to the zm homepage
7) Click Options
8) Check the checkbox named "OPT_USE_AUTH"
9) Click Save on the options page
10) It takes you to the login page
11) Enter admin;admin and click Login
12) It takes me to the above mentioned error page and does not let me into zoneminder

The docker container's log doesn't have anything interesting:
```
Starting pre-service scritps in /etc/my_init.d
*** Running: /etc/my_init.d/startup.sh
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
Database already at version 1.34.6, update skipped.
starting rc.local scritps
Booting runit daemon...
Process runsvdir running with PID 223
```

The log inside the container has some interesting errors:
```
root@361ff3bee67e:/# cat /var/log/apache2/error.log
[Tue Mar 17 11:41:55.814526 2020] [mpm_prefork:notice] [pid 232] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Tue Mar 17 11:41:55.814584 2020] [core:notice] [pid 232] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
[Tue Mar 17 11:43:59.936805 2020] [php7:warn] [pid 236] [client 192.168.4.101:58874] PHP Warning:  error_log(/var/log/zm/web_php.log): failed to open stream: Permission denied in /usr/share/zoneminder/www/includes/logger.php on line 397, referer: http://podman:1080/zm/index.php?view=login
[Tue Mar 17 11:43:59.936848 2020] [php7:error] [pid 236] [client 192.168.4.101:58874] PHP Fatal error:  Can't write to log file '/var/log/zm/web_php.log': error_log(/var/log/zm/web_php.log): failed to open stream: Permission denied @ /usr/share/zoneminder/www/includes/logger.php/397 in /usr/share/zoneminder/www/includes/logger.php on line 400, referer: http://podman:1080/zm/index.php?view=login
[Tue Mar 17 11:45:12.942656 2020] [php7:warn] [pid 233] [client 192.168.4.101:58913] PHP Warning:  error_log(/var/log/zm/web_php.log): failed to open stream: Permission denied in /usr/share/zoneminder/www/includes/logger.php on line 397, referer: http://podman:1080/zm/
[Tue Mar 17 11:45:12.942700 2020] [php7:error] [pid 233] [client 192.168.4.101:58913] PHP Fatal error:  Can't write to log file '/var/log/zm/web_php.log': error_log(/var/log/zm/web_php.log): failed to open stream: Permission denied @ /usr/share/zoneminder/www/includes/logger.php/397 in /usr/share/zoneminder/www/includes/logger.php on line 400, referer: http://podman:1080/zm/[Tue Mar 17 11:45:31.127261 2020] [php7:warn] [pid 318] [client 192.168.4.101:59000] PHP Warning:  error_log(/var/log/zm/web_php.log): failed to open stream: Permission denied in /usr/share/zoneminder/www/includes/logger.php on line 397, referer: http://podman:1080/zm/[Tue Mar 17 11:45:31.127441 2020] [php7:error] [pid 318] [client 192.168.4.101:59000] PHP Fatal error:  Can't write to log file '/var/log/zm/web_php.log': error_log(/var/log/zm/web_php.log): failed to open stream: Permission denied @ /usr/share/zoneminder/www/includes/logger.php/397 in /usr/share/zoneminder/www/includes/logger.php on line 400, referer: http://podman:1080/zm/
```

**Comment by angelrr7702** [comment]
appear relate to this : 

DEFAULT CHARACTER SET latin1

https://forums.zoneminder.com/viewtopic.php?t=26005

Other discrepancy with   quantumobject/docker-zoneminder is 

  -v /home/jeremy/zoneminder/events:/var/lib/zoneminder/events

normal I use the complete folder 

-v /home/xxxxx/zoneminder:/var/lib/zoneminder

where you have 4 folders .. 

events/
images/
temp/
cache/
plus the file configured

sincerely
Angel Rodriguez

**Comment by Germs2004** [comment]
> " Make the following changes:
> character-set-server = latin1
> collation-server = latin1_swedish_ci
> Note: The above settings are actually the Mariadb default. Changing back to default is necessary to avoid errors when logging into Zoneminder. "

Ok, I tried again three times using each of these three commands, but had the same problem with all of them:
1) using mariadb's default settings
`docker exec -i $DatabaseContainerName mysql -u$ROOTUSR -p$ROOTPWD -e "CREATE DATABASE ${NEWDBNAME};"`
2) using the word "default" when setting both charset and collate
`docker exec -i $DatabaseContainerName mysql -u$ROOTUSR -p$ROOTPWD -e "CREATE DATABASE ${NEWDBNAME} DEFAULT CHARACTER SET latin1 DEFAULT COLLATE latin1_swedish_ci;"`
3) without the word "default" when setting both charset and collate
`docker exec -i $DatabaseContainerName mysql -u$ROOTUSR -p$ROOTPWD -e "CREATE DATABASE ${NEWDBNAME} CHARACTER SET latin1 COLLATE latin1_swedish_ci;"`

But your next suggestion worked.  I replaced this
```
-v /home/jeremy/zoneminder/events:/var/lib/zoneminder/events \
-v /home/jeremy/zoneminder/logs:/var/log/zm \
```
with this
```
-v /home/jeremy/zoneminder:/var/lib/zoneminder \
```
and that solved the problem. Now, I can enable "OPT_USE_AUTH", click save, and log in successfully with admin;admin.  I guess those permission errors I mentioned in my first post were related to these paths.  Thank you for your help!

**Comment by angelrr7702** [comment]
sorry I got confuse too ,,, folder was /var/cache/zoneminder  that where is  

events/
images/
temp/
cache/

**Comment by angelrr7702** [comment]
and that will create other problem that I'm fixing now ..

**Comment by angelrr7702** [comment]
done, with a new build of container . 
fix problem relate to  : 

 /var/cache/zoneminder
